# Generated by Django 5.2 on 2025-04-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C2', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrnews',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='C2.category'),
        ),
    ]
