# Generated by Django 5.2 on 2025-05-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C2', '0003_alter_mrnews_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
